In [2]:
import tensorflow as tf

In [3]:
lvl1_tensor = tf.Variable([323, 2321, 334], tf.int16)

In [4]:
lvl2_tensor = tf.Variable([[23.43, 34.23], [12.2, 1.56], [23.9, 43.5]], tf.float64)

In [5]:
tf.rank(lvl1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
lvl2_tensor.shape

TensorShape([3, 2])

In [33]:
tensor1 = tf.ones([4, 2, 1])
tensor2 = tf.reshape(tensor1, [2, 2, 2])
tensor3 = tf.reshape(tensor2, [2, -1])

In [34]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(4, 2, 1), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)
